version: '{build}'
image: Visual Studio 2017
build_script:
- ps: .\build.ps1 --target=AppVeyor --configuration=Release
test: off
artifacts:
- path: .\artifacts\NppXmlTreeviewPlugin_*.zip
  name: nppxmltreeview
deploy:
- provider: GitHub
  tag: Rome v$(appveyor_build_version)
  release: NppTreeViewPlugin Rome v$(appveyor_build_version)
  auth_token:
    secure: yYYP2c1jtrjIbccXBUjTmCqdGWnI5AxPgNUfNhjZZrpA81Y+DKsGh3wamK/pOSMt
  artifact: 
  draft: true
  on:
    branch: master