version: 1.1.0.{build}
skip_tags: true
os: Visual Studio 2015
configuration: Release
assembly_info:
  patch: true
  file: '**\VersionInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
- cmd: '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat"'
build:
  verbosity: minimal
after_build:
- ps: 7z a NppXMLTreeviewPlugin.zip c:\projects\NppXmlTreeview\src\NppXmlTreeviewPlugin\bin\Release\NppXmlTreeviewPlugin.dll
artifacts:
- path: NppXmlTreeviewPlugin.zip
  name: nppxmltreeview
deploy:
- provider: GitHub
  tag: Aveiro v$(appveyor_build_version)
  release: NppTreeViewPlugin Aveiro v$(appveyor_build_version)
  auth_token:
    secure: yYYP2c1jtrjIbccXBUjTmCqdGWnI5AxPgNUfNhjZZrpA81Y+DKsGh3wamK/pOSMt
  artifact: 
  draft: true
  on:
    branch: master
